version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  firebase-emulator:
    image: andreysenov/firebase-tools
    ports:
      - "9099:9099" # Auth
      - "8080:8080" # Firestore
      - "9199:9199" # Storage
      - "4000:4000" # Emulator UI
    volumes:
      - ./firebase.json:/app/firebase.json
      - ./firestore.rules:/app/firestore.rules
      - ./storage.rules:/app/storage.rules
    command: firebase emulators:start --only auth,firestore,storage --project demo-project